name: CI

on: [ push ]

jobs:
  hooks:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: 'x64'
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest and build coverage reports
        run: |
          pytest test --cov=src --cov-report=html:doc/source/_static/codecov --cov-report=json
      - name: Upload coverage data
        uses: actions/upload-artifact@v3
        with:
          name: covdata
          path: |
            echo $PWD
            ls
            .coverage.*
      - name: Upload coverage data html
        uses: actions/upload-artifact@v3
        with:
          name: covdata-html
          path: doc/source/_static/codecov


  coverage-reports:
    name: coverage
    needs: test
    # if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download coverage data
        uses: actions/download-artifact@v3
        with:
          name: covdata
      - name: Download coverage data html
        uses: actions/download-artifact@v3
        with:
          name: covdata-html
      - name: build website for detailed coverage
        run: |
          pip install sphinx
          cd doc
          make html
          cd ..
      - name: deploy website
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: doc/build/html
      - name: Create json for badge
        run: |
          export TOTAL=$(python -c "import json;print(json.load(open('coverage.json'))['totals']['percent_covered_display'])")
          echo "total=$TOTAL" >> $GITHUB_ENV
          echo "### Total coverage: ${TOTAL}%" >> $GITHUB_STEP_SUMMARY
      - name: Make badge
        uses: schneegans/dynamic-badges-action@v1.4.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gistID: eIVWGt8ZoNX25cxgpXOeUW2wXPyQAktvx4CWrYzspt50VuaXB
          filename: covbadge.json
          label: Coverage
          message: ${{ env.total }}%
          minColorRange: 50
          maxColorRange: 95
          valColorRange: ${{ env.total }}
